version: "3"

services:
  mysqlserver:
    image: mysql:5.7
    container_name: mysqlserver
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    restart: always
